### ISSUE TITLE
can't install dependencies in venv

### ISSUE THREAD

**Issue by kloebner** [plotly/dash-vanguard-report#17]
when following the instructions for running locally, trying to install the requirements in an otherwise functional virtualenv gives:

> (venv) username$ pip install -r requirements.txt 
> Exception:
> Traceback (most recent call last):
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
>     status = self.run(options, args)
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 289, in run
>     self.name, wheel_cache
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 289, in populate_requirement_set
>     use_pep517=options.use_pep517):
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 112, in parse_requirements
>     for req in req_iter:
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 193, in process_line
>     isolated=isolated, options=req_options, wheel_cache=wheel_cache
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 239, in install_req_from_line
>     looks_like_dir = os.path.isdir(p) and (
>   File "path/to/dash-vanguard-report/venv/lib/python3.7/genericpath.py", line 42, in isdir
>     st = os.stat(s)
> ValueError: embedded null byte

**Comment by mrcartier** [comment]
Don't know if you resolved it or not @kloebner but my issue was when cloning the repo the requirements.txt file was blank(tried 2X before I noticed). Created new .txt, then copied & pasted directly from [here](https://github.com/plotly/dash-vanguard-report/blob/master/requirements.txt). Install went fine & it's working now. Also you need to use http://127.0.0.1:8050/dash-vanguard-report as the url or else you'll get a 404 (it's discussed in a separate issue).
